/**
 * Claude Code export adapter.
 *
 * 입력 : .harness/team.json, .harness/skills-map.json, .harness/quality-policy.md, .harness/orchestrator.md
 * 출력 : .claude/agents/*.md, .claude/skills/*.md, CLAUDE.md (포인터)
 *
 * 규칙 :
 * - 단방향. `.claude/` 를 읽지 않는다.
 * - 결정적. 동일 입력 → 동일 출력.
 * - 화이트리스트 외 경로 접근 금지.
 */
import { mkdir, readFile, writeFile, stat } from "node:fs/promises";
import { join, isAbsolute, relative, sep } from "node:path";

export const ALLOWED_INPUTS = [
  "team.json",
  "skills-map.json",
  "quality-policy.md",
  "orchestrator.md",
  "harness-design.md"
] as const;

const OUTPUT_ROOT_REL = ".claude";
const OUTPUT_SUBDIRS = ["agents", "skills"];

export interface ExportClaudeInput {
  cwd: string;
}

export interface ExportClaudeResult {
  agents: string[];
  skills: string[];
  pointer: string;
}

export class ExportPathViolationError extends Error {
  readonly exitCode = 70;
  constructor(path: string) {
    super(`export blocked: path outside whitelist: ${path}`);
    this.name = "ExportPathViolationError";
  }
}

export class ExportPrecondError extends Error {
  readonly exitCode = 10;
  constructor(missing: string) {
    super(`export requires ${missing} (run earlier stages)`);
    this.name = "ExportPrecondError";
  }
}

interface TeamJson {
  pattern: string;
  agents: Array<{
    id: string;
    role: string;
    owns: string[];
    skillsCandidates?: string[];
  }>;
}

interface SkillsMapJson {
  mappings: Array<{ agentId: string; skills: string[]; notes?: string }>;
}

function checkPath(p: string, base: string): void {
  if (isAbsolute(p)) throw new ExportPathViolationError(p);
  const rel = relative(base, join(base, p));
  if (rel.startsWith("..") || rel.includes(`..${sep}`)) {
    throw new ExportPathViolationError(p);
  }
}

export async function readInputFile(
  harnessRoot: string,
  name: string
): Promise<string> {
  if (!ALLOWED_INPUTS.includes(name as (typeof ALLOWED_INPUTS)[number])) {
    throw new ExportPathViolationError(name);
  }
  checkPath(name, harnessRoot);
  return readFile(join(harnessRoot, name), "utf8");
}

export async function exportClaude(
  input: ExportClaudeInput
): Promise<ExportClaudeResult> {
  const harnessRoot = join(input.cwd, ".harness");
  try {
    await stat(harnessRoot);
  } catch {
    throw new ExportPrecondError(".harness/ (run `harness init` first)");
  }
  try {
    await stat(join(harnessRoot, "team.json"));
  } catch {
    throw new ExportPrecondError("team.json (run `harness design`)");
  }

  const team: TeamJson = JSON.parse(await readInputFile(harnessRoot, "team.json"));
  const skillsMapText = await readInputFile(harnessRoot, "skills-map.json").catch(
    () => null
  );
  const skillsMap: SkillsMapJson = skillsMapText
    ? JSON.parse(skillsMapText)
    : { mappings: [] };

  const outRoot = join(input.cwd, OUTPUT_ROOT_REL);
  for (const sub of OUTPUT_SUBDIRS) {
    await mkdir(join(outRoot, sub), { recursive: true });
  }

  const agentFiles: string[] = [];
  for (const agent of team.agents) {
    const file = join(outRoot, "agents", `${agent.id}.md`);
    const skillsRow =
      skillsMap.mappings.find((m) => m.agentId === agent.id)?.skills ?? [];
    const md = [
      `---`,
      `id: ${agent.id}`,
      `role: ${agent.role}`,
      `pattern: ${team.pattern}`,
      `---`,
      "",
      `# ${agent.id} (${agent.role})`,
      "",
      `- owns: ${agent.owns.join(", ")}`,
      `- skills: ${skillsRow.join(", ")}`,
      "",
      `Generated from .harness/team.json by harness export claude.`,
      ""
    ].join("\n");
    await writeFile(file, md, "utf8");
    agentFiles.push(file);
  }

  const skillIds = Array.from(
    new Set(skillsMap.mappings.flatMap((m) => m.skills))
  );
  const skillFiles: string[] = [];
  for (const id of skillIds) {
    const file = join(outRoot, "skills", `${id}.md`);
    const md = [
      `---`,
      `id: ${id}`,
      `---`,
      "",
      `# ${id}`,
      "",
      `referenced by agents in .harness/skills-map.json`,
      ""
    ].join("\n");
    await writeFile(file, md, "utf8");
    skillFiles.push(file);
  }

  const pointer = join(input.cwd, "CLAUDE.md");
  const pointerMd = [
    `# CLAUDE.md`,
    "",
    `This file is generated by \`harness export claude\`.`,
    "",
    `Source of truth: \`.harness/\` (do not edit \`.claude/\` directly).`,
    "",
    `- team pattern: ${team.pattern}`,
    `- agents: ${team.agents.map((a) => a.id).join(", ")}`,
    ""
  ].join("\n");
  await writeFile(pointer, pointerMd, "utf8");

  return { agents: agentFiles, skills: skillFiles, pointer };
}
